export type {
  InsightCategory,
  InsightLevel,
  InsightKind,
  ScopeKind,
  Position,
  Range,
  ScopeRef,
  ScopeNode,
  TypeInferenceData,
  NullabilityData,
  SmartCastData,
  ScopingData,
  ExtensionData,
  LambdaParam,
  LambdaData,
  OverloadData,
  OperatorData,
  ReceiverData,
  DelegationData,
  DestructuringData,
  InsightData,
  SemanticInsight,
  SemanticProfile,
} from "@shared/types";
